sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: qh+S5PEFeLu2Ag8Ll7TA+fgsBgvUGyDj3IKXurjiTLYW0LCaPR3t9MxxP32ayqrNefHO+hOBUn2PMWS4tc1//DcTJp40Mlwwfd3pdURIWTeK6pPQaFNns/GNmPFBs32D0WQLUrCUrtKpwLG1/JONwnZJtVHl/P3TMjf+8HPm5bgeRU6Ro6PjYYxvu2NRgG7I0CwrcwJAF2kR+SnlCZT7tBJm5S4c5midr7syNjWBYaao5Oe1e4Z+Ax7URsxDR38YZ9JT4j7yJwXZW7wLVGp0SI8FBtLQDJSIlpKiYMWkMLCz4Dw9J1XFNmqgggp7kHHulMJP92eezKDB9JhF3NGpGeDTjTtC8uHyWW1RhZZASv1RE382CctbKpXvhW+2GuN+fJjwgK4nMlwJJOgtzoM7g9uZZwEvY7Igqal5Ids+DMun+qP7UPE5T2jWr9R/ixdbnTgXyPtPXaxeVKGAmXDKL5JAEwW8jLzy2/kk5Uxd5FYNwI5sN8g0cJ5JqI4dYx+wnsGjyqv6iw0yYOMYNqKjTvebbWOOXhlFSvHhEI3HiaFfAQ5Fpi0xvN+8zzA8brLcqvk1+upahr4TunLijpefF0eiEHcxBKTwZB5XvLmxrBx/GWeraT54jecYsFRInvmh4mIgt1OALAWR2BBKKVstrQ0267vwz8blOixT7hl6JU8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Miracle-Mongers-and-Their-Methods--13-A-Complete-Expos--of-the-Modus-Operandi-of-Fire-Eaters-He__435
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy